apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app  
  template:
    metadata:
      labels:
        app: web-app  
    spec:
      containers:
      - name: web-app
        image: aml51/web-app  
        imagePullPolicy: Always
        ports:
        - containerPort: 8081  
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"

