pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "aml51/web-app"
        DOCKER_CREDENTIALS = "docker-hub-credentials"
        KUBECONFIG_CREDENTIALS = "kubeconfig-file"
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    echo "📥 Fetching code from GitHub..."
                    checkout scm: [
                        $class: 'GitSCM',
                        branches: [[name: '*/main']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [[$class: 'CloneOption', depth: 1, noTags: false]],
                        userRemoteConfigs: [[url: 'https://github.com/Amlali5/CloudDevOpsProject.git']]
                    ]
                }
            }
        }

        stage('Check Maven Version') {
            steps {
                script {
                    echo "🔍 Checking Maven version..."
                    sh 'mvn -v'
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    echo "🔨 Building the app..."
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    echo "🧪 Running unit tests..."
                    sh 'mvn test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "🐳 Building Docker Image..."
                    sh "docker build -t $DOCKER_IMAGE:${env.BUILD_NUMBER} ."
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    echo "🚀 Pushing Docker Image to Docker Hub..."
                    withDockerRegistry([credentialsId: DOCKER_CREDENTIALS, url: 'https://index.docker.io/v1/']) {
                        sh "docker push $DOCKER_IMAGE:${env.BUILD_NUMBER} --verbose"
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    echo "📦 Deploying to Kubernetes..."
                    withCredentials([file(credentialsId: KUBECONFIG_CREDENTIALS, variable: 'KUBECONFIG')]) {
                        sh "kubectl set image deployment/web-app web-app=$DOCKER_IMAGE:${env.BUILD_NUMBER} --kubeconfig=$KUBECONFIG"
                    }
                }
            }
        }

        stage('Verify Kubernetes Deployment') {
            steps {
                script {
                    echo "🔍 Verifying Kubernetes Deployment..."
                    sh "kubectl get pods --kubeconfig=$KUBECONFIG"
                }
            }
        }
    }
}
